In [5]:
import pandas as pd
df = pd.read_csv(r'C:\Users\admin\superstore-sales-analysis\data\superstore.csv.zip', encoding='latin1')
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,è®°å½æ°,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [4]:
import os
print(os.listdir(r'C:\Users\admin\superstore-sales-analysis\data'))

['superstore.csv.zip']

In [1]:
import os
print(os.listdir(r'C:\Users\admin\superstore-sales-analysis\data'))

['superstore.csv', 'superstore.csv.zip']

In [4]:
import os
folder = r'C:\Users\admin\superstore-sales-analysis\data\superstore.csv'
print(os.listdir(folder))

['superstore.csv']

In [5]:
import pandas as pd
df = pd.read_csv(r'C:\Users\admin\superstore-sales-analysis\data\superstore.csv\superstore.csv', encoding='latin1')
df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,è®°å½æ°,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,1,2011-01-07 00:00:00.000,CA-2011-130813,...,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,1,2011-01-21 00:00:00.000,CA-2011-148614,...,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,1,2011-08-05 00:00:00.000,CA-2011-118962,...,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,1,2011-09-29 00:00:00.000,CA-2011-146969,...,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

In [6]:
df.shape

(51290, 27)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   è®°å½æ°       51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

In [8]:
df.describe()

,Discount,è®°å½æ°,Profit,Quantity,Row.ID,Sales,Shipping.Cost,Year,weeknum
count,51290.000000,51290.0,51290.000000,51290.000000,51290.00000,51290.000000,51290.000000,51290.000000,51290.000000
mean,0.142908,1.0,28.610982,3.476545,25645.50000,246.498440,26.375818,2012.777208,31.287112
std,0.212280,0.0,174.340972,2.278766,14806.29199,487.567175,57.296810,1.098931,14.429795
min,0.000000,1.0,-6599.978000,1.000000,1.00000,0.000000,0.002000,2011.000000,1.000000
25%,0.000000,1.0,0.000000,2.000000,12823.25000,31.000000,2.610000,2012.000000,20.000000
50%,0.000000,1.0,9.240000,3.000000,25645.50000,85.000000,7.790000,2013.000000,33.000000
75%,0.200000,1.0,36.810000,5.000000,38467.75000,251.000000,24.450000,2014.000000,44.000000
max,0.850000,1.0,8399.976000,14.000000,51290.00000,22638.000000,933.570000,2014.000000,53.000000

In [9]:
df.isnull().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
è®°å½æ°         0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\admin\superstore-sales-analysis\data\superstore.csv\superstore.csv', encoding='latin1')

In [4]:
df_utf8 = pd.read_csv(r'C:\Users\admin\superstore-sales-analysis\data\superstore.csv\superstore.csv', encoding='utf-8')
print(df_utf8.columns.tolist())

['Category', 'City', 'Country', 'Customer.ID', 'Customer.Name', 'Discount', 'Market', '记录数', 'Order.Date', 'Order.ID', 'Order.Priority', 'Product.ID', 'Product.Name', 'Profit', 'Quantity', 'Region', 'Row.ID', 'Sales', 'Segment', 'Ship.Date', 'Ship.Mode', 'Shipping.Cost', 'State', 'Sub.Category', 'Year', 'Market2', 'weeknum']

In [5]:
df = pd.read_csv(r'C:\Users\admin\superstore-sales-analysis\data\superstore.csv\superstore.csv', encoding='utf-8')
df.columns.tolist()

['Category',
 'City',
 'Country',
 'Customer.ID',
 'Customer.Name',
 'Discount',
 'Market',
 '记录数',
 'Order.Date',
 'Order.ID',
 'Order.Priority',
 'Product.ID',
 'Product.Name',
 'Profit',
 'Quantity',
 'Region',
 'Row.ID',
 'Sales',
 'Segment',
 'Ship.Date',
 'Ship.Mode',
 'Shipping.Cost',
 'State',
 'Sub.Category',
 'Year',
 'Market2',
 'weeknum']

In [6]:
df = df.rename(columns={'记录数': 'Record.Count'})
df.columns.tolist()

['Category',
 'City',
 'Country',
 'Customer.ID',
 'Customer.Name',
 'Discount',
 'Market',
 'Record.Count',
 'Order.Date',
 'Order.ID',
 'Order.Priority',
 'Product.ID',
 'Product.Name',
 'Profit',
 'Quantity',
 'Region',
 'Row.ID',
 'Sales',
 'Segment',
 'Ship.Date',
 'Ship.Mode',
 'Shipping.Cost',
 'State',
 'Sub.Category',
 'Year',
 'Market2',
 'weeknum']

In [7]:
print("عدد الصفوف المكررة بالكامل:", df.duplicated().sum())

عدد الصفوف المكررة بالكامل: 0

In [8]:
print(df['Order.Date'].head())
print(df['Order.Date'].dtype)

0    2011-01-07 00:00:00.000
1    2011-01-21 00:00:00.000
2    2011-08-05 00:00:00.000
3    2011-08-05 00:00:00.000
4    2011-09-29 00:00:00.000
Name: Order.Date, dtype: object
object

In [9]:
df['Order.Date'] = pd.to_datetime(df['Order.Date'])
print(df['Order.Date'].dtype)
print(df['Order.Date'].head())

datetime64[ns]
0   2011-01-07
1   2011-01-21
2   2011-08-05
3   2011-08-05
4   2011-09-29
Name: Order.Date, dtype: datetime64[ns]

In [10]:
print(df['Ship.Date'].dtype)

object

In [11]:
df['Ship.Date'] = pd.to_datetime(df['Ship.Date'])

In [12]:
print(df['Ship.Date'].dtype)
print(df['Ship.Date'].head())

datetime64[ns]
0   2011-01-09
1   2011-01-26
2   2011-08-09
3   2011-08-09
4   2011-10-03
Name: Ship.Date, dtype: datetime64[ns]

In [13]:
print("أكبر 5 قيم خسارة (Profit سالب):")
print(df.nsmallest(5, 'Profit')[['Product.Name', 'Sales', 'Profit', 'Discount']])

print("\nأكبر 5 قيم ربح:")
print(df.nlargest(5, 'Profit')[['Product.Name', 'Sales', 'Profit', 'Discount']])

أكبر 5 قيم خسارة (Profit سالب):
                                    Product.Name  Sales     Profit  Discount
47074  Cubify CubeX 3D Printer Double Head Print   4500 -6599.9780       0.7
29353             Motorola Smart Phone, Cordless   3085 -4088.3760       0.6
47388  Cubify CubeX 3D Printer Triple Head Print   8000 -3839.9904       0.5
46422  GBC DocuBind P400 Electric Binding System   2178 -3701.8928       0.8
47414  Lexmark MX611dhe Monochrome Laser Printer   2550 -3399.9800       0.7

أكبر 5 قيم ربح:
                                           Product.Name  Sales     Profit  \
27727             Canon imageCLASS 2200 Advanced Copier  17500  8399.9760
28327             Canon imageCLASS 2200 Advanced Copier  14000  6719.9808
27524             Canon imageCLASS 2200 Advanced Copier  10500  5039.9856
3092   GBC Ibimaster 500 Manual ProClick Binding System   9893  4946.3700
2722               Ibico EPK-21 Electric Binding System   9450  4630.4755

       Discount
27727       0.0
28327       0.0
27524       0.0
3092        0.0
2722        0.0

In [14]:
print("عدد الصفوف اللي فيها Sales سالبة أو صفر:", (df['Sales'] <= 0).sum())

عدد الصفوف اللي فيها Sales سالبة أو صفر: 1

In [15]:
df[df['Sales'] <= 0]

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,Record.Count,Order.Date,Order.ID,...,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
46158,Office Supplies,Houston,United States,ZC-219104,Zuschuss Carroll,0.8,US,1,2014-06-20,US-2014-102288,...,0,Consumer,2014-06-24,Standard Class,0.01,Texas,Appliances,2014,North America,25

In [16]:
# تأكد من نطاق أعمدة الأرقام المهمة
print(df[['Sales', 'Profit', 'Discount', 'Quantity']].describe())

              Sales        Profit      Discount      Quantity
count  51290.000000  51290.000000  51290.000000  51290.000000
mean     246.498440     28.610982      0.142908      3.476545
std      487.567175    174.340972      0.212280      2.278766
min        0.000000  -6599.978000      0.000000      1.000000
25%       31.000000      0.000000      0.000000      2.000000
50%       85.000000      9.240000      0.000000      3.000000
75%      251.000000     36.810000      0.200000      5.000000
max    22638.000000   8399.976000      0.850000     14.000000

In [17]:
# تأكد من عدد القيم الفريدة في أعمدة نصية مهمة (اكتشاف أخطاء إملائية محتملة)
print(df['Category'].unique())
print(df['Segment'].unique())
print(df['Region'].unique())

['Office Supplies' 'Technology' 'Furniture']
['Consumer' 'Home Office' 'Corporate']
['West' 'East' 'South' 'Central' 'Africa' 'Central Asia' 'North Asia'
 'Caribbean' 'North' 'EMEA' 'Oceania' 'Southeast Asia' 'Canada']